# Generated by Django 5.1.7 on 2025-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Study', 'Study'), ('Personal', 'Personal'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
